x-common-params: &common-params
  image: offchainlabs/nitro-node:${NITRO_VERSION}
  entrypoint: /usr/local/bin/nitro
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  redis:
    image: redis:6.2.6
    ports:
      - "127.0.0.1:6379:6379"

  sequencer:
    <<: *common-params
    command: [ "--conf.file", "/config/sequencer_config.json", "--node.feed.output.enable", "--node.feed.output.port", "9642", "--http.api", "net,web3,eth,txpool", "--node.seq-coordinator.my-url", "ws://sequencer:8548", "--graphql.enable", "--graphql.vhosts", "*", "--graphql.corsdomain", "*" ]
    volumes:
      - "./data/seq-data:/home/user/.arbitrum/local/nitro"
      - "./configs:/config"
      - "./data/tokenbridge-data:/tokenbridge-data"
    ports:
      - "127.0.0.1:8347:8547"
      - "127.0.0.1:8348:8548"
      - "127.0.0.1:9642:9642"
    depends_on:
      - redis

  sequencer_b:
    <<: *common-params
    ports:
      - "127.0.0.1:8647:8547"
      - "127.0.0.1:8648:8548"
    volumes:
      - "./data/seq-data-b:/home/user/.arbitrum/local/nitro"
      - "./configs:/config"
    command: --conf.file /config/sequencer_config.json --node.seq-coordinator.my-url ws://sequencer_b:8548
    depends_on:
      - redis

  sequencer_c:
    <<: *common-params
    ports:
      - "127.0.0.1:8747:8547"
      - "127.0.0.1:8748:8548"
    volumes:
      - "./data/seq-data-c:/home/user/.arbitrum/local/nitro"
      - "./configs:/config"
    command: --conf.file /config/sequencer_config.json --node.seq-coordinator.my-url ws://sequencer_c:8548
    depends_on:
      - redis

  # TODO add batch poster private key to command args
  poster:
    <<: *common-params
    command: [ "--conf.file", "/config/poster_config.json", "--node.batch-poster.parent-chain-wallet.private-key", "${BATCH_POSTER_PRIVATE_KEY}", "--node.batch-poster.data-poster.redis-signer.signing-key", "${BATCH_POSTER_REDIS_SIGNING_KEY}" ]
    volumes:
      - "./data/poster-data:/home/user/.arbitrum/local/nitro"
      - "./configs:/config"
    ports:
      - "127.0.0.1:8147:8547"
      - "127.0.0.1:8148:8548"
    depends_on:
      - redis

  poster_b:
    <<: *common-params
    command: [ "--conf.file", "/config/poster_config.json", "--node.batch-poster.parent-chain-wallet.private-key", "${BATCH_POSTER_PRIVATE_KEY}", "--node.batch-poster.data-poster.redis-signer.signing-key", "${BATCH_POSTER_REDIS_SIGNING_KEY}" ]
    volumes:
      - "./data/poster-data-b:/home/user/.arbitrum/local/nitro"
      - "./configs:/config"
    ports:
      - "127.0.0.1:9147:8547"
      - "127.0.0.1:9148:8548"
    depends_on:
      - redis

  poster_c:
    <<: *common-params
    command: [ "--conf.file", "/config/poster_config.json", "--node.batch-poster.parent-chain-wallet.private-key", "${BATCH_POSTER_PRIVATE_KEY}", "--node.batch-poster.data-poster.redis-signer.signing-key", "${BATCH_POSTER_REDIS_SIGNING_KEY}" ]
    volumes:
      - "./data/poster-data-c:/home/user/.arbitrum/local/nitro"
      - "./configs:/config"
    ports:
      - "127.0.0.1:9247:8547"
      - "127.0.0.1:9248:8548"
    depends_on:
      - redis

  # TODO add validator private key to command args
  validator:
    <<: *common-params
    ports:
      - "127.0.0.1:8247:8547"
      - "127.0.0.1:8248:8548"
    volumes:
      - "./data/validator-data:/home/user/.arbitrum/local/nitro"
      - "./configs:/config"
    command: --conf.file /config/validator_config.json --http.port 8547 --http.api net,web3,arb --ws.port 8548 --node.staker.parent-chain-wallet.private-key ${VALIDATOR_PRIVATE_KEY}
    depends_on:
      - sequencer
      - validation_node

  validation_node:
    <<: *common-params
    entrypoint: /usr/local/bin/nitro-val
    ports:
      - "127.0.0.1:8949:8549"
    volumes:
      - "./configs:/config"
    command: --conf.file /config/validation_node_config.json
