x-common-params: &common-params
  image: offchainlabs/nitro-node:${NITRO_VERSION}
  entrypoint: /usr/local/bin/nitro
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  sequencer:
    <<: *common-params
    command: [
      "--conf.file", "/config/sequencer_config.json", 
      "--node.feed.output.enable", 
      "--node.feed.output.port", "9642", 
      "--http.api", "net,web3,eth,txpool,arb", 
      "--node.batch-poster.parent-chain-wallet.private-key", "${BATCH_POSTER_PRIVATE_KEY}",
      "--node.staker.parent-chain-wallet.private-key", "${VALIDATOR_PRIVATE_KEY}"
    ]
    volumes:
      - "seq-data-a:/home/user/.arbitrum/local/nitro"
      - "./configs:/config"
      - "tokenbridge-data:/tokenbridge-data"
    ports:
      - "127.0.0.1:8347:8547"
      - "127.0.0.1:8348:8548"
      - "127.0.0.1:9642:9642"
volumes:
  seq-data-a:
  tokenbridge-data: